### PR TITLE
Compiler warnings.  Also: bugs revealed by warnings

### PR DESCRIPTION
**Pull request by xloem**
One of these is a missing return from a logdb function which in my opinion should have been a build error.  It would be good to figure out what compiler flag to change to make that happen. (edit: second commit adds that)

### CODE REVIEW

**Comment by jsarenik** [comment]
One of the tests failed with this:

```
src/random.c:107:1: error: control reaches end of non-void function [-Werror=return-type]
```

**Comment by xloem** [comment]
This one looks like a bug in github.  The pair of failing tests ran on commit https://github.com/libbtc/libbtc/commit/3dcc90603cb114eb4d13e19a86a6d64883417a76 which is not shown as the present tip of this pull request for me; the present tip appears to me to be https://github.com/libbtc/libbtc/pull/180/commits/5d018427cab9403e3aeb5ac03dae6108546ad4ad, which is actually a fix for that very issue.  I'll force-push a new commit to retrigger the tests.

**Comment by xloem** [comment]
todo: there is an additional build warning on windows, shown in the same travis output, regarding an undefined symbol.  this may also represent a serious underlying error.

**Comment by jsarenik** [comment]
ACK c702004124678c599ba6b50e024d3acfd7b5c582

**Comment by xloem** [comment]
I didn't see acknowledgement from you that 5d01842 from yesterday is exactly the same as c702004 from today, and attempted to upload tags to verify that was true, but accidentally uploaded tags from many other repositories too.

It's important to me resolve that, but it is too confusing [and incapacitatingly triggering] for me to do right now.  I might end up taking a break from this repository for a while, as mentioned earlier.

Sorry for all the conversational noise.  Thanks so much for your comments; they really helped move things forward.

**Comment by xloem** [comment]
I'll add the tags and the undefined symbols as new issues and merge this, since the return value bugs are pretty important.

**Review by jsarenik — APPROVED** [review]
Looks good to me. Thanks!

**Comment by xloem** [comment]
@jsarenik thank you so much for merging these two pull requests during my scatteredness.  Are you able to confirm that the fix I pushed was the same as the original commit, it just worked around a github/travis ci display error?  We'll want to migrate to a better CI setup if the error was real and they continue.

**Comment by jsarenik** [comment]
@xloem Good question about the verification. Never again will I press the magit Github button again, but rather rebase and force-push. But yes, it seems to have done the right thing. It made an empty 9b340e0 merge-commit which is not nice and would not be there if I did rebase instead.

**Comment by xloem** [comment]
- [ ] verify that jsarenik saw the github/travis error by referencing specific commit ids.  they are speaking as if they did not experience it.

**Comment by jsarenik** [comment]
@xloem https://travis-ci.org/github/libbtc/libbtc/builds/765965064 is the testrun of d9f8294 so no, I did not see any error (while the only "pipelines" seem to be travis and coverails, no github CI).

**Pull request merged**
