### PR TITLE
build: Remove generated file libbtc.pc

### PR DESCRIPTION
**Pull request by laanwj**
The file `libbtc.pc` is generated from `libbtc.pc.in` by `configure`, so there is no need to store it in the repository (it will just cause false positives for git).

### CODE REVIEW

**Comment by promag** [comment]
Add to `.gitignore`?

**Comment by laanwj** [comment]
@promag Good idea, done

**Comment by promag** [comment]
ACK 3e547a0.

**Comment by jonasschnelli** [comment]
ACK 3e547a0bc21207a58457a89642d2b2bd30bfa687

**Pull request merged**
